main: com.rex2go.claimme.ClaimMe
name: ${name}
version: ${version}
author: rex2go
api-version: 1.19
loadbefore:
  - Vault
  - WorldEdit
  - WorldGuard
depend:
  - Vault
  - WorldEdit
  - WorldGuard
commands:
  claim:
    description: Claim a chunk
  plot:
    description: Manage claimed area (plot)
  lastseen:
    description: Check last online time of a player
